### ISSUE TITLE
Question Documentation

### ISSUE THREAD

**Issue by SteinerPascal** [StatistikStadtZuerich/ld-data#176]
Hi, I'm currently doing my master thesis and i would like to use the ld-data from the city of zurich. But currently I'm a bit lost. I don't really know what kind of information is available. Do you have an Ontology or a schema description of the taxonomy & vocabulary used in your datasets?

The link for the documentation: https://data.stadt-zuerich.ch/dataset/stadt_zuerich_losd#dataset is unfortunately broken.

**Comment by hjstalder** [comment]
Hi Pascal, 
The documentation on https://github.com/statistikstadtzuerich/documentation is not really up to date. That's why it was only "private". I set it to "public" again.

Only a few datasets from a proof of concept are currently available on ld.stadt-zuerich.ch. A project is currently underway to put all of our own Open Government Data on LINDAS. The project should be completed by the end of the year.
In the coming weeks, this data will be available at https://ld.integ.stadt-zuerich.ch/.well-known/void and https://ld.stadt-zuerich.ch/.well-known/void respectively .

If you have any questions, you are welcome to contact hansjoerg.stalder@zuerich.ch and rolf.schenker.ssz@zuerich.ch.

Here are a few useful links:

https://github.com/zazuko/cube-link
https://zazuko.github.io/cube-link/
https://github.com/zazuko/trifid
https://data.stadt-zuerich.ch/showcase?q=zazuko&sort=score+desc%2C+date_last_modified+desc 

I hope this information helps you. Best regards, Hansjörg

**Comment by SteinerPascal** [comment]
Thank you a lot! I will definitely reach out to you within the next couple of weeks.

**Comment by ktk** [comment]
@SteinerPascal we are switching everything to https://cube.link/ schema right now, as @hjstalder mentioned. 

You can get an overview of the cubes-in-progress here: https://s.zazuko.com/eRzyFt

Some years back I did a video about querying RDF cubes. The schema I mention there is *not* anymore what we are using but the principle remains the same, we have observations and dimensions per cube: https://www.youtube.com/watch?v=IUyzwwwIJSk

If you need a better entry, let us know and I will create some queries for you.

**Comment by ktk** [comment]
This would be an entry point into "Wirtschaftliche Wohnbevölkerung", which is pretty much one of the simplest cubes available:

https://s.zazuko.com/cu4qKm

You can lookup an observation itself, but you have to add `integ` to the link as this is not yet on the production endpoint:

https://ld.integ.stadt-zuerich.ch/statistics/000003/observation/XXX0000-XXX0000-XXX0000-XXX0000-XXX0000-R00011-Z31121941

**Comment by SteinerPascal** [comment]
Thanks for the information provided. That looks already really cool! Let me have a look at it and then come back to you. I would like to make a PoC including my rewrite of SparNatural:
https://github.com/SteinerPascal/sparnatural-port
I think that could be interesting for you as well.

**Comment by ktk** [comment]
Ok great, if you want to do something with SparNatural you might want to have a look at our query library, it abstracts a lot of things for cubes behind a JavaScript API: https://github.com/zazuko/rdf-cube-view-query

We use this internally for query builders & alike.

**Comment by ktk** [comment]
Closing here, please followup if we can help again.
